# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)
print (arr)
arr.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
import numpy as np

In [7]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10 , dtype = int).reshape(2,5)
print(arr1,arr2)
np.vstack((arr1,arr2))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
import numpy as np

In [11]:
arr1 =  np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype= int).reshape(2,5)
print((arr1,arr2))
np.hstack((arr1,arr2))

(array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]]))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
import numpy as np

In [13]:
arr= np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr)
arr.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [ ]:
import numpy as np

In [14]:
arr = np.arange(15).reshape(1,3,5)
print(arr.ndim,"Dimension")
print(arr)
arr=arr.flatten()
print(arr.ndim,"Dimension")
arr

3 Dimension
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
1 Dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [15]:
import numpy as np

In [16]:
arr = np.arange(15).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
import numpy as np

In [18]:
arr = np.arange(25).reshape(5,5)
print(arr)
np.square(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [23]:
import numpy as np

In [51]:

arr=np.arange(30).reshape(5,6)
print(arr)
arr.mean()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [26]:
import numpy as np

In [49]:

arr=np.arange(30).reshape(5,6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [42]:
np.std(arr)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [35]:
import numpy as np

In [48]:

arr=np.arange(30).reshape(5,6)
print(arr)
np.median(arr)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [52]:
import numpy as np

In [54]:
np.random.seed(123)
arr = np.random.randint(30, size = (5,6))
arr

array([[13,  2, 28,  2,  6, 17],
       [19, 10, 27, 25, 22,  1],
       [ 0, 17, 15,  9,  0, 14],
       [ 0, 15, 25, 19, 14, 29],
       [ 4,  0, 16,  4, 17, 23]])

In [55]:
arr.T

array([[13, 19,  0,  0,  4],
       [ 2, 10, 17, 15,  0],
       [28, 27, 15, 25, 16],
       [ 2, 25,  9, 19,  4],
       [ 6, 22,  0, 14, 17],
       [17,  1, 14, 29, 23]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [56]:
import numpy as np

In [60]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.diagonal(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [58]:
import numpy as np

In [59]:
arr = np.arange(16).reshape(4,4)
print(arr)
np.linalg.det(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [61]:
import numpy as np

In [64]:
arr = np.arange(10)
print(arr)
print(np.percentile(arr,5))
print(np.percentile(arr,95))

[0 1 2 3 4 5 6 7 8 9]
0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [3]:
import numpy as np

In [4]:
arr = np.arange(30).reshape(5,6)
print(arr)
np.isnan(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])